name: Release Plugin

env:
  PLUGIN_NAME: duplicate-post-preserve-date

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build-test-image:
    runs-on: ubuntu-22.04
    timeout-minutes: 6

    steps:
      - name: Checkout files
        timeout-minutes: 1
        uses: actions/checkout@v4
        with:
          ref: main

      # Get the version number
      - name: Get the version number
        id: get-version-number
        run: |
          # Get the release from ${{ env.PLUGIN_NAME }}.php file, e.g. * Version: 4.0.0
          VERSION_NUMBER=$(grep -oP 'Version:\s+\K[0-9]+\.[0-9]+\.[0-9]+' "${{ env.PLUGIN_NAME }}.php")
          if [ ! "${VERSION_NUMBER}" ]; then
              echo "Error! Release number not found."
              exit 1
          fi
          echo "Release number: ${VERSION_NUMBER}"
           echo "VERSION_NUMBER=${VERSION_NUMBER}" >> $GITHUB_OUTPUT

      # Install Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21

      # Build the plugin
      - name: Build the plugin
        run: |
          npm install
          npm run build
          mkdir -p "${{ env.PLUGIN_NAME }}"
          cp -r index.php "${{ env.PLUGIN_NAME }}.php" LICENSE.md README.md build includes "${{ env.PLUGIN_NAME }}/"

      # Zip up the plugin into a release PLUGIN_NAME
      - name: Zip up the plugin`
        run: |
          if [ ! -d "${{ env.PLUGIN_NAME }}" ]; then
              echo "Error! Plugin directory not found."
              exit 1
          fi
          zip -r "plugin.zip" "${{ env.PLUGIN_NAME }}"
          ls -l "plugin.zip"

      # Create a release
      - name: Create a release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "v${{ steps.get-version-number.outputs.VERSION_NUMBER }}" "plugin.zip" --title "v${{ steps.get-version-number.outputs.VERSION_NUMBER }}" --notes "Release ${VERSION_NUMBER}"
